import type { Metadata } from "next";
import { Questrial } from "next/font/google";
import "./globals.css";

// Configure the Questrial font
const questrial = Questrial({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-questrial",
});

export const metadata: Metadata = {
  title: "Olyvio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={questrial.variable}>
      <body className={`${questrial.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}